# Name ID Department

Clara Magdy Ghaly, 20221424647, Healthcare

Khaled Ahmed Mansour Ahmed, 20221320444, AI

Doaa Samir Elsayed, 2103114, AI

Basmala Akram Hegazy, 2103159, AI

Aml Ibrahim Mohamed, 20221443988, Cybersecurity

Suhaila Adel Ali, 20221376543, Cybersecurity

Menna Allah Ahmed Saad, 2106212, Cybersecurity

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("/content/networkintrusion.csv")
df

duration protocol_type   service  flag  src_bytes  dst_bytes  land  \
0             0           tcp   private   REJ        0.0        0.0     0   
1             0           tcp   private   REJ        0.0        0.0     0   
2             2           tcp  ftp_data    SF    12983.0        0.0     0   
3             0          icmp     eco_i    SF       20.0        0.0     0   
4             1           tcp    telnet  RSTO        0.0       15.0     0   
...         ...           ...       ...   ...        ...        ...   ...   
22539         0           tcp      smtp    SF      794.0      333.0     0   
22540         0           tcp      http    SF      317.0      938.0     0   
22541         0           tcp      http    SF    54540.0     8314.0     0   
22542         0           udp  domain_u    SF       42.0       42.0     0   
22543         0           tcp    sunrpc   REJ        0.0        0.0     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                   0       0    0  ...                  10   
1                   0       0    0  ...                   1   
2                   0       0    0  ...                  86   
3                   0       0    0  ...                  57   
4                   0       0    0  ...                  86   
...               ...     ...  ...  ...                 ...   
22539               0       0    0  ...                 141   
22540               0       0    0  ...                 255   
22541               0       0    2  ...                 255   
22542               0       0    0  ...                 252   
22543               0       0    0  ...                  21   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        0.04                    0.06   
1                        0.00                    0.06   
2                        0.61                    0.04   
3                        1.00                    0.00   
4                        0.31                    0.17   
...                       ...                     ...   
22539                    0.72                    0.06   
22540                    1.00                    0.00   
22541                    1.00                    0.00   
22542                    0.99                    0.01   
22543                    0.08                    0.03   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                             0.00                         0.00   
1                             0.00                         0.00   
2                             0.61                         0.02   
3                             1.00                         0.28   
4                             0.03                         0.02   
...                            ...                          ...   
22539                         0.01                         0.01   
22540                         0.01                         0.01   
22541                         0.00                         0.00   
22542                         0.00                         0.00   
22543                         0.00                         0.00   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                      0.00                       0.0                  1.00   
1                      0.00                       0.0                  1.00   
2                      0.00                       0.0                  0.00   
3                      0.00                       0.0                  0.00   
4                      0.00                       0.0                  0.83   
...                     ...                       ...                   ...   
22539                  0.01                       0.0                  0.00   
22540                  0.01                       0.0                  0.00   
22541                  0.00                       0.0                  0.07   
22542                  0.00                  

In [3]:
df.shape

(22544, 40)

# Data Preprocessing

### Describe Method
Describe() method returns description that contains numerical of the data in the dataset.

count - The number of not-empty values.

mean - The average (mean) value.

std - The standard deviation.

min - the minimum value.

25% - The 25% percentile.

50% - The 50% percentile.

75% - The 75% percentile.

max - the maximum value.

In [4]:
df.describe()

duration     src_bytes     dst_bytes          land  wrong_fragment  \
count  22544.000000  2.253800e+04  2.253800e+04  22544.000000    22544.000000   
mean     218.859076  1.039812e+04  2.055584e+03      0.000311        0.008428   
std     1407.176612  4.728493e+05  2.122190e+04      0.017619        0.142599   
min        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
25%        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
50%        0.000000  5.400000e+01  4.600000e+01      0.000000        0.000000   
75%        0.000000  2.870000e+02  6.010000e+02      0.000000        0.000000   
max    57715.000000  6.282565e+07  1.345927e+06      1.000000        3.000000   

             urgent           hot  num_failed_logins     logged_in  \
count  22544.000000  22544.000000       22544.000000  22544.000000   
mean       0.000710      0.105394           0.021647      0.442202   
std        0.036473      0.928428           0.150328      0.496659   
min        0.000000      0.000000           0.000000      0.000000   
25%        0.000000      0.000000           0.000000      0.000000   
50%        0.000000      0.000000           0.000000      0.000000   
75%        0.000000      0.000000           0.000000      1.000000   
max        3.000000    101.000000           4.000000      1.000000   

       num_compromised  ...  dst_host_count  dst_host_srv_count  \
count     22544.000000  ...    22544.000000        22544.000000   
mean          0.119899  ...      193.869411          140.750532   
std           7.269597  ...       94.035663          111.783972   
min           0.000000  ...        0.000000            0.000000   
25%           0.000000  ...      121.000000           15.000000   
50%           0.000000  ...      255.000000          168.000000   
75%           0.000000  ...      255.000000          255.000000   
max         796.000000  ...      255.000000          255.000000   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count            22544.000000            22544.000000   
mean                 0.608722                0.090540   
std                  0.435688                0.220717   
min                  0.000000                0.000000   
25%                  0.070000                0.000000   
50%                  0.920000                0.010000   
75%                  1.000000                0.060000   
max                  1.000000                1.000000   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                 22544.000000                 22544.000000   
mean                      0.132261                     0.019638   
std                       0.306268                     0.085394   
min                       0.000000                     0.000000   
25%                       0.000000                     0.000000   
50%                       0.000000                     0.000000   
75%                       0.030000                     0.010000   
max                       1.000000                     1.000000   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count          22544.000000              22544.000000          22544.000000   
mean               0.097814                  0.099426              0.233385   
std                0.273139                  0.281866              0.387229   
min                0.000000                  0.000000              0.000000   
25%                0.000000                  0.000000              0.000000   
50%                0.000000                  0.000000              0.000000   
75%                0.000000                  0.000000              0.360000   
max                1.000000                  1.000000              1.000000   

       dst_host_srv_rerror_rate  
count              22544.000000  
mean                   0.226683  
std                    0.400875  
min                    0.000000  
25%                    0.000000  
50%         

### Handling Missing Values
Here we check how many missing values in each column

In [5]:
# Check for missing values
print("Before handling missing values:\n", df.isnull().sum())

Before handling missing values:
 duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      6
dst_bytes                      6
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
num_root                       0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          9
srv_count                      9
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_c

### Filling the missing values in src_bytes, dst_bytes, count and srv_count with mean of each column

In [6]:
df['src_bytes'].fillna(value=df['src_bytes'].mean(), inplace=True)

In [7]:
df['dst_bytes'].fillna(value=df['dst_bytes'].mean(), inplace=True)

In [8]:
df['count'].fillna(value=df['count'].mean(), inplace=True)

In [9]:
df['srv_count'].fillna(value=df['srv_count'].mean(), inplace=True)

In [10]:
print("After handling missing values:\n", df.isnull().sum())

After handling missing values:
 duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
num_root                       0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_co

### Handling Duplicate data
Here we check if there are duplicated rows in all the dataset and the output shows as boolean. 'False' indicates that there is no duplication and 'True' indicates that there are 2 or more rows duplicated

In [11]:
duplicates = df[df.duplicated()]
duplicates

duration protocol_type service flag  src_bytes  dst_bytes  land  \
10256         0           tcp   other  REJ        0.0        0.0     0   
10619         0           tcp   other  REJ        0.0        0.0     0   
15044         0           tcp   other  REJ        0.0        0.0     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
10256               0       0    0  ...                   1   
10619               0       0    0  ...                   1   
15044               0       0    0  ...                   1   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
10256                     0.0                     1.0   
10619                     0.0                     1.0   
15044                     0.0                     1.0   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
10256                          0.0                          0.0   
10619                          0.0                          0.0   
15044                          0.0                          0.0   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
10256                  0.07                       0.0                  0.93   
10619                  0.03                       0.0                  0.97   
15044                  0.02                       0.0                  0.98   

       dst_host_srv_rerror_rate    class  
10256                       1.0  anomaly  
10619                       1.0  anomaly  
15044                       1.0  anomaly  

[3 rows x 40 columns]

In [12]:
# Drop duplicates
df.drop_duplicates(inplace=True)

In [13]:
df.shape

(22541, 40)

### Handling Structural Error
Data type Conversion: Here we will be checking the data types of each column and see if it matches the dataset or not

In [14]:
df.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                      float64
dst_bytes                      float64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
num_root                         int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                          float64
srv_count                      float64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate          

In [15]:
# I changed the data type of the column src_bytes since it's considered as float and it should be converted into an integer for better results
df['src_bytes'] = df['src_bytes'].astype(int)

In [16]:
# I changed the data type of the dst_bytes since it's considered as float and it should be converted into an integer for better results
df['dst_bytes'] = df['dst_bytes'].astype(int)

In [17]:
# I changed the data type of the column count since it's considered as float and it should be converted into an integer for better results
df['count'] = df['count'].astype(int)

In [18]:
# I changed the data type of the column srv_count since it's considered as float and it should be converted into an integer for better results
df['srv_count'] = df['srv_count'].astype(int)

In [19]:
# I changed the data type of the column class since it's considered as object and it should be converted into an integer for better results
# 0 represents normal
# 1 represents anomaly
df['class'] = df['class'].apply(lambda x: 1 if x == 'anomaly' else 0)
df

duration protocol_type   service  flag  src_bytes  dst_bytes  land  \
0             0           tcp   private   REJ          0          0     0   
1             0           tcp   private   REJ          0          0     0   
2             2           tcp  ftp_data    SF      12983          0     0   
3             0          icmp     eco_i    SF         20          0     0   
4             1           tcp    telnet  RSTO          0         15     0   
...         ...           ...       ...   ...        ...        ...   ...   
22539         0           tcp      smtp    SF        794        333     0   
22540         0           tcp      http    SF        317        938     0   
22541         0           tcp      http    SF      54540       8314     0   
22542         0           udp  domain_u    SF         42         42     0   
22543         0           tcp    sunrpc   REJ          0          0     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                   0       0    0  ...                  10   
1                   0       0    0  ...                   1   
2                   0       0    0  ...                  86   
3                   0       0    0  ...                  57   
4                   0       0    0  ...                  86   
...               ...     ...  ...  ...                 ...   
22539               0       0    0  ...                 141   
22540               0       0    0  ...                 255   
22541               0       0    2  ...                 255   
22542               0       0    0  ...                 252   
22543               0       0    0  ...                  21   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        0.04                    0.06   
1                        0.00                    0.06   
2                        0.61                    0.04   
3                        1.00                    0.00   
4                        0.31                    0.17   
...                       ...                     ...   
22539                    0.72                    0.06   
22540                    1.00                    0.00   
22541                    1.00                    0.00   
22542                    0.99                    0.01   
22543                    0.08                    0.03   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                             0.00                         0.00   
1                             0.00                         0.00   
2                             0.61                         0.02   
3                             1.00                         0.28   
4                             0.03                         0.02   
...                            ...                          ...   
22539                         0.01                         0.01   
22540                         0.01                         0.01   
22541                         0.00                         0.00   
22542                         0.00                         0.00   
22543                         0.00                         0.00   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                      0.00                       0.0                  1.00   
1                      0.00                       0.0                  1.00   
2                      0.00                       0.0                  0.00   
3                      0.00                       0.0                  0.00   
4                      0.00                       0.0                  0.83   
...                     ...                       ...                   ...   
22539                  0.01                       0.0                  0.00   
22540                  0.01                       0.0                  0.00   
22541                  0.00                       0.0                  0.07   
22542                  0.00                  

In [20]:
df.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
num_root                         int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate          

### Separating Numerical and Categorical features

In [21]:
# Finding numerical columns
num_col = df._get_numeric_data().columns

# Finding categorical columns
cat_col = list(set(df.columns) - set(num_col))

print('Categorical :', cat_col)
print('Numerical :', num_col)

Categorical : ['protocol_type', 'flag', 'service']
Numerical : Index(['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
       'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised',
       'root_shell', 'num_root', 'num_shells', 'num_access_files',
       'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count',
       'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate',
       'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
       'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
       'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate',
       'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'class'],
      dtype='object')


# Encode categorical features

In [22]:
# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Encode categorical features in the same DataFrame
for column in df.columns:
    if df[column].dtype == 'object':  # Check if the column contains categorical data
        df[column] = label_encoder.fit_transform(df[column])

In [23]:
df

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0             0              1       45     1          0          0     0   
1             0              1       45     1          0          0     0   
2             2              1       19     9      12983          0     0   
3             0              0       13     9         20          0     0   
4             1              1       55     2          0         15     0   
...         ...            ...      ...   ...        ...        ...   ...   
22539         0              1       49     9        794        333     0   
22540         0              1       22     9        317        938     0   
22541         0              1       22     9      54540       8314     0   
22542         0              2       11     9         42         42     0   
22543         0              1       52     1          0          0     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                   0       0    0  ...                  10   
1                   0       0    0  ...                   1   
2                   0       0    0  ...                  86   
3                   0       0    0  ...                  57   
4                   0       0    0  ...                  86   
...               ...     ...  ...  ...                 ...   
22539               0       0    0  ...                 141   
22540               0       0    0  ...                 255   
22541               0       0    2  ...                 255   
22542               0       0    0  ...                 252   
22543               0       0    0  ...                  21   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        0.04                    0.06   
1                        0.00                    0.06   
2                        0.61                    0.04   
3                        1.00                    0.00   
4                        0.31                    0.17   
...                       ...                     ...   
22539                    0.72                    0.06   
22540                    1.00                    0.00   
22541                    1.00                    0.00   
22542                    0.99                    0.01   
22543                    0.08                    0.03   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                             0.00                         0.00   
1                             0.00                         0.00   
2                             0.61                         0.02   
3                             1.00                         0.28   
4                             0.03                         0.02   
...                            ...                          ...   
22539                         0.01                         0.01   
22540                         0.01                         0.01   
22541                         0.00                         0.00   
22542                         0.00                         0.00   
22543                         0.00                         0.00   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                      0.00                       0.0                  1.00   
1                      0.00                       0.0                  1.00   
2                      0.00                       0.0                  0.00   
3                      0.00                       0.0                  0.00   
4                      0.00                       0.0                  0.83   
...                     ...                       ...                   ...   
22539                  0.01                       0.0                  0.00   
22540                  0.01                       0.0                  0.00   
22541                  0.00                       0.0                  0.07   
22542                  0.00                  

### Handling Outliers

In [24]:
# Calculate Z-Score for each numeric column
z_scores = df.apply(lambda x: np.abs(stats.zscore(x)))

# Define a threshold for Z-Score
threshold = 3

# Identify and mark outliers based on the threshold
outliers = (z_scores > threshold).any(axis=1)

# Remove outliers from the DataFrame and create a new DataFrame without outliers
df_no_outliers = df[~outliers]

# Print the DataFrame without outliers
print("\nDataFrame without outliers:")
df_no_outliers


DataFrame without outliers:


duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0             0              1       45     1          0          0     0   
1             0              1       45     1          0          0     0   
2             2              1       19     9      12983          0     0   
4             1              1       55     2          0         15     0   
5             0              1       22     9        267      14515     0   
...         ...            ...      ...   ...        ...        ...   ...   
22538         0              0       14     9       1032          0     0   
22539         0              1       49     9        794        333     0   
22540         0              1       22     9        317        938     0   
22541         0              1       22     9      54540       8314     0   
22542         0              2       11     9         42         42     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                   0       0    0  ...                  10   
1                   0       0    0  ...                   1   
2                   0       0    0  ...                  86   
4                   0       0    0  ...                  86   
5                   0       0    0  ...                 255   
...               ...     ...  ...  ...                 ...   
22538               0       0    0  ...                 255   
22539               0       0    0  ...                 141   
22540               0       0    0  ...                 255   
22541               0       0    2  ...                 255   
22542               0       0    0  ...                 252   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        0.04                    0.06   
1                        0.00                    0.06   
2                        0.61                    0.04   
4                        0.31                    0.17   
5                        1.00                    0.00   
...                       ...                     ...   
22538                    1.00                    0.00   
22539                    0.72                    0.06   
22540                    1.00                    0.00   
22541                    1.00                    0.00   
22542                    0.99                    0.01   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                             0.00                         0.00   
1                             0.00                         0.00   
2                             0.61                         0.02   
4                             0.03                         0.02   
5                             0.01                         0.03   
...                            ...                          ...   
22538                         1.00                         0.00   
22539                         0.01                         0.01   
22540                         0.01                         0.01   
22541                         0.00                         0.00   
22542                         0.00                         0.00   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                      0.00                       0.0                  1.00   
1                      0.00                       0.0                  1.00   
2                      0.00                       0.0                  0.00   
4                      0.00                       0.0                  0.83   
5                      0.01                       0.0                  0.00   
...                     ...                       ...                   ...   
22538                  0.00                       0.0                  0.00   
22539                  0.01                       0.0                  0.00   
22540                  0.01                       0.0                  0.00   
22541                  0.00                  

### Checking the balance of 'class' columns

In [25]:
# The count of unque values in the 'loan_status' column
count_values = df_no_outliers['class'].value_counts()
count_values

class
0    8441
1    6868
Name: count, dtype: int64

### Handling the imbalance

In [26]:
# pip install --upgrade scikit-learn imbalanced-learn
# pip install --upgrade imbalanced-learn
# pip install imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Assuming df is your DataFrame with 'class' column containing binary labels (0 and 1)
# X should contain your feature columns and y should contain the target variable ('class')

# Separate features (X) and target variable (y)
X = df_no_outliers.drop(columns=['class'])
y = df_no_outliers['class']

# Initialize RandomOverSampler
ros = RandomOverSampler(random_state=42)

# Resample the dataset
X_resampled, y_resampled = ros.fit_resample(X, y)

# Create a new DataFrame with balanced classes
balanced_df = pd.concat([pd.DataFrame(X_resampled, columns=X.columns), pd.DataFrame(y_resampled, columns=['class'])], axis=1)


### After Balancing

In [27]:
# The count of unique values in the 'loan_status' column
count_values = balanced_df['class'].value_counts()
count_values

class
1    8441
0    8441
Name: count, dtype: int64

###  Data Normalization

In [28]:
scaler = MinMaxScaler()

# Fit and transform the numerical columns using the scaler
df1 = scaler.fit_transform(X_resampled)

In [29]:
df1

array([[0.00000000e+00, 5.00000000e-01, 7.14285714e-01, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 5.00000000e-01, 7.14285714e-01, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [5.40248514e-04, 5.00000000e-01, 3.01587302e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 5.00000000e-01, 7.14285714e-01, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 5.00000000e-01, 7.14285714e-01, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 5.00000000e-01, 8.73015873e-01, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

### Saving the target attribute into another list for future analysis perpose

In [30]:
target_col=balanced_df['class']

### Splitting the dataset into training and testing

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
# Total number of rows
total_rows = df1.shape[0]

# Desired number of rows for the test set
desired_test_rows = 500

# Calculate the test size
test_size = desired_test_rows / total_rows

# Perform train-test split with the calculated test size
X_train, X_test, y_train, y_test = train_test_split(df1, target_col, test_size=test_size, random_state=42)

# Checking the shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (16382, 39)
X_test shape: (500, 39)
y_test shape: (500,)


### Random Forest

In [32]:
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)

RandomForestClassifier()

In [33]:
y_pred = model.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.976


In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       247
           1       0.98      0.98      0.98       253

    accuracy                           0.98       500
   macro avg       0.98      0.98      0.98       500
weighted avg       0.98      0.98      0.98       500



### Decision Tree

In [35]:
from sklearn.tree import DecisionTreeClassifier
model_d = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
model_d.fit(X_train, y_train)


y_pred_d = model_d.predict(X_test)
print(accuracy_score(y_test,y_pred_d))

0.924


In [36]:
print(classification_report(y_test,y_pred_d))

              precision    recall  f1-score   support

           0       0.98      0.86      0.92       247
           1       0.88      0.98      0.93       253

    accuracy                           0.92       500
   macro avg       0.93      0.92      0.92       500
weighted avg       0.93      0.92      0.92       500



### Support Vector Machine

In [37]:
from sklearn.svm import SVC
from sklearn import metrics

In [38]:
clf = SVC(kernel="linear")
clf.fit(X_train, y_train)

predict = clf.predict(X_test)

ac_score = metrics.accuracy_score(y_test, predict)
cl_report = metrics.classification_report(y_test, predict)
print(cl_report)

              precision    recall  f1-score   support

           0       0.97      0.89      0.93       247
           1       0.90      0.97      0.94       253

    accuracy                           0.93       500
   macro avg       0.93      0.93      0.93       500
weighted avg       0.93      0.93      0.93       500



### Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
model_l = LogisticRegression(max_iter=1200000)

model_l.fit(X_train, y_train)


y_pred_l = model_l.predict(X_test)
print(accuracy_score(y_test,y_pred_l))

0.934


In [40]:
print(classification_report(y_test,y_pred_l))

              precision    recall  f1-score   support

           0       0.96      0.91      0.93       247
           1       0.91      0.96      0.94       253

    accuracy                           0.93       500
   macro avg       0.94      0.93      0.93       500
weighted avg       0.94      0.93      0.93       500



### Visualization

In [41]:
!apt install -y libboost-all-dev
!pip install -U pip
!pip install "pybind11[global]"

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libboost-all-dev is already the newest version (1.74.0.3ubuntu7).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.


In [42]:
!pip install aijack

In [43]:
import os
import time
import copy

import numpy as np
import sklearn
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from aijack.attack import Evasion_attack_sklearn

In [44]:
X_minus_1 = X_train
attacker = Evasion_attack_sklearn(
    target_model=clf,
    dmax=(8441/ 255) * 2.5,
    X_minus_1=X_minus_1,
    max_iter=300,
    gamma=1 / (X_train.shape[1] * np.var(X_train)),
    lam=10,
    t=0.5,
    h=10,
)
n=[]
for i in range (0,X_test.shape[0]):
    x0 = X_test[i]
    xm, g_list = attacker.attack(copy.copy(x0))
    y_pred = clf.predict(xm.reshape(1,-1))
    n.append(y_pred)

In [45]:
n

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [46]:
arr = np.array(n)
arr_reshaped = arr.reshape(-1, 1)

In [47]:
arr_reshaped

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [48]:
print(accuracy_score(y_test,arr_reshaped))

0.494


### Neural Network
Building the Model

In [83]:
import tensorflow as tf #for the model building
from sklearn.metrics import classification_report, confusion_matrix #for the classification report

In [84]:
# Define the neural network architecture with additional layers and regularization
model = tf.keras.Sequential([
    # Input layer with 128 neurons, ReLU activation function, and L2 regularization
    tf.keras.layers.Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001), input_shape=(X.shape[1],)),
    # Dropout layer with dropout rate of 0.5 to prevent overfitting
    tf.keras.layers.Dropout(0.5),
    # Hidden layer with 64 neurons, ReLU activation function, and L2 regularization
    tf.keras.layers.Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    tf.keras.layers.Dropout(0.5),
    # Hidden layer with 32 neurons, ReLU activation function, and L2 regularization
    tf.keras.layers.Dense(32, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    tf.keras.layers.Dropout(0.5),
    # Output layer with 1 neuron and sigmoid activation function for binary classification
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [85]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/20
256/256 [==============================] - 4s 7ms/step - loss: 0.4711 - accuracy: 0.8459 - val_loss: 0.2650 - val_accuracy: 0.9280
Epoch 2/20
256/256 [==============================] - 1s 5ms/step - loss: 0.2581 - accuracy: 0.9349 - val_loss: 0.2118 - val_accuracy: 0.9460
Epoch 3/20
256/256 [==============================] - 1s 5ms/step - loss: 0.2106 - accuracy: 0.9450 - val_loss: 0.1872 - val_accuracy: 0.9480
Epoch 4/20
256/256 [==============================] - 2s 6ms/step - loss: 0.1903 - accuracy: 0.9476 - val_loss: 0.1779 - val_accuracy: 0.9420
Epoch 5/20
256/256 [==============================] - 2s 7ms/step - loss: 0.1738 - accuracy: 0.9510 - val_loss: 0.1619 - val_accuracy: 0.9440
Epoch 6/20
256/256 [==============================] - 1s 5ms/step - loss: 0.1640 - accuracy: 0.9524 - val_loss: 0.1556 - val_accuracy: 0.9420
Epoch 7/20
256/256 [==============================] - 1s 4ms/step - loss: 0.1572 - accuracy: 0.9523 - val_loss: 0.1508 - val_accuracy: 0.9460
Epoch 

In [86]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_accuracy)

16/16 [==============================] - 0s 3ms/step - loss: 0.1316 - accuracy: 0.9540
Test Accuracy: 0.9539999961853027


In [87]:
from tensorflow.keras.callbacks import EarlyStopping

In [88]:
def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Reshape((X_train.shape[1], 1), input_shape=(X_train.shape[1],)),  # Reshape input for convolutional layer
        tf.keras.layers.Conv1D(64, kernel_size=3, activation='relu', padding='same'),
        tf.keras.layers.MaxPooling1D(pool_size=2),
        tf.keras.layers.Conv1D(128, kernel_size=3, activation='relu', padding='same'),
        tf.keras.layers.MaxPooling1D(pool_size=2),
        tf.keras.layers.Conv1D(256, kernel_size=3, activation='relu', padding='same'),
        tf.keras.layers.MaxPooling1D(pool_size=2),
        # Spatial Pyramid Pooling layer
        tf.keras.layers.GlobalAveragePooling1D(),  # Global Average Pooling
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])
    return model

In [89]:
# Create  neural network model
model_1 = create_model()


# Compile the model
model_1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [90]:
# Define early stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train the model with early stopping
history = model_1.fit(X_train, y_train, epochs=50, batch_size=128, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/50
103/103 [==============================] - 10s 84ms/step - loss: 0.3255 - accuracy: 0.8533 - val_loss: 0.1761 - val_accuracy: 0.9371
Epoch 2/50
103/103 [==============================] - 7s 63ms/step - loss: 0.1532 - accuracy: 0.9414 - val_loss: 0.1536 - val_accuracy: 0.9411
Epoch 3/50
103/103 [==============================] - 4s 42ms/step - loss: 0.1330 - accuracy: 0.9474 - val_loss: 0.1369 - val_accuracy: 0.9448
Epoch 4/50
103/103 [==============================] - 6s 59ms/step - loss: 0.1247 - accuracy: 0.9519 - val_loss: 0.1438 - val_accuracy: 0.9451
Epoch 5/50
103/103 [==============================] - 4s 43ms/step - loss: 0.1110 - accuracy: 0.9569 - val_loss: 0.1215 - val_accuracy: 0.9536
Epoch 6/50
103/103 [==============================] - 4s 42ms/step - loss: 0.1097 - accuracy: 0.9550 - val_loss: 0.1156 - val_accuracy: 0.9567
Epoch 7/50
103/103 [==============================] - 6s 60ms/step - loss: 0.1030 - accuracy: 0.9576 - val_loss: 0.1183 - val_accuracy: 0.956

In [91]:
# Predict probabilities on test data
y_pred_probs = model_1.predict(X_test)

# Threshold probabilities to get predicted classes
y_pred = (y_pred_probs > 0.5).astype(int)

16/16 [==============================] - 0s 5ms/step


In [92]:
# Generate classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       247
           1       0.96      0.98      0.97       253

    accuracy                           0.97       500
   macro avg       0.97      0.97      0.97       500
weighted avg       0.97      0.97      0.97       500

